#!/bin/sh

image="/tmp/pluck/screen.png"
icon="/tmp/pluck/icon.png"
dependencies="xinput xdotool import"
cr="\033[1;31m"
cg="\033[1;32m"
cb="\033[1;34m"

#help function
help() { printf "${cg}pluck: a x11 color picker
Usage: pluck ${cb}[rgb|h]${cg}
${cb}  rgb:${cg} use rgb value instead of hex
${cb}    h:${cg} help
${cr}Report issues at: https://github.com/manas140/pluck/\n" && exit; }

#main funtion
main() {
  eval $(xdotool getmouselocation --shell)

  for a in $(import -window root -crop "1x1+$X+$Y" -depth 8 txt:); do
    case $a in
      \#*) hex=$a;;
      \(*\)) rgb=$a;;
    esac 
  done

  case $color_type in 
    rgb) color=$rgb;;
    hex) color=$hex;;
  esac
  
  #optional dependencies
  if $(type xclip >/dev/null); then
    printf "$color\n" | xclip -sel c 
  else 
    printf "\r$color             \n"
  fi
  
  if $(type notify-send >/dev/null); then
    convert -size 64x64 xc:"$hex" "$icon"
    notify-send "pluck" "$color" --icon="$icon"
  fi
  exit
}

#arguments
case "$1" in
  *rgb*) color_type="rgb";;
  *h*) help;;
  *) color_type="hex";;
esac

#check dependencies
for dep in $dependencies; do
  if ! type $dep >/dev/null; then
    printf "${cr}$dep Not Found\n" && exit 1;
  else 
    printf "${cg}Click On The Pixel\r${cr}"
  fi
done

#get id (EOF needs perfect tabs)
while read -r a; do 
  case $a in 
	*Mouse*|*mouse*) mouse_id="$(xinput list --id-only "$a")";;
	*touchpad*|*Touchpad*) touchpad_id="$(xinput list --id-only "$a")";;
  esac;
done <<-EOF
$(xinput list --name-only)
EOF

#get click
while true; do
  case $touchpad_id in
    "") touchpad="no";;
    *) for a in $(xinput query-state $touchpad_id); do
        case $a in
          *down*) main;;
        esac
      done
  esac
  case $mouse_id in
    "") if [ "$touchpad" = "no" ]; then 
          printf "${cr}[-] No Touch Device Found\n" && exit 1;
        else 
          continue
        fi;;
    *) for a in $(xinput query-state $mouse_id); do
        case $a in
          *down*) main;;
        esac
      done 
  esac
done
